services:
  - type: web
    name: eglise-sainte-famille-bingerville
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /var/data
      - key: UPLOADS_DIR
        value: /var/data/images
    disk:
      name: paroisse-data
      mountPath: /var/data
      sizeGB: 1
